logging:
  level: DEBUG
  logfile: /dev/stdout
metadata:
  contact:
    address: Martin-Luther-King-Weg 24
    city: "M\xFCnster"
    country: Germany
    email: j.schnell@52north.org
    fax: lol
    hours: Mo-Fr 09:00-16:00 CE(S)T
    instructions: During hours of service. Off on weekends.
    name: 52North
    phone: +49-251-396371-0
    position: Operator
    postalcode: 48155
    role: pointOfContact
    stateorprovince: NRW
    url: https://52north.org/about-us/contact-us/
  identification:
    description: pygeoapi provides an API to geospatial data
    keywords:
    - geospatial
    - data
    - api
    - living-labs
    - atrai
    - 52north
    - reedu
    keywords_type: theme
    terms_of_service: ''
    title: pygeoapi atrai
    url: localhost
  license:
    name: 'FIXME: TBD, maybe CC-BY 4.0 license'
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: atrai bikes project
    url: https://atrai.bike
resources:
  bumpy-roads:
    processor:
      name: atrai_processes.BumpyRoads
    type: process
  calculate_statistics:
    processor:
      name: atrai_processes.Statistics
    type: process
  dangerous-places:
    processor:
      name: atrai_processes.DangerousPlaces
    type: process
  distances:
    processor:
      name: atrai_processes.Distances
    type: process
  osem_data_ingestion:
    processor:
      name: atrai_processes.OsemDataIngestion
    type: process
  pm-analysis:
    processor:
      name: atrai_processes.PMAnalysis
    type: process
  road_network:
    processor:
      name: atrai_processes.RoadNetwork
    type: process
  speed-traffic-flow:
    processor:
      name: atrai_processes.SpeedTrafficFlow
    type: process
  temperature:
    processor:
      name: atrai_processes.Temperature
    type: process
server:
  bind:
    host: 0.0.0.0
    port: 80
  cors: true
  encoding: utf-8
  gzip: false
  language: en-US
  limit: 10
  manager:
    connection: /tmp/pygeoapi-process-manager.db
    name: TinyDB
    output_dir: /tmp/
  map:
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  mimetype: application/json; charset=UTF-8
  ogc_schemas_location: /schemas.opengis.net
  pretty_print: true
  url: /
