services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
    ports:
      - "5000:80"
    environment:
      - INT_API_TOKEN=token
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_SERV_CONFIG=/pygeoapi/local.config.yml

