services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
      - ./html:/pygeoapi/data/html
    ports:
      - "5000:80"
    environment:
      - INT_API_TOKEN=token
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_SERV_CONFIG=/pygeoapi/local.config.yml
      - DATABASE_URL=postgresql://postgres:postgres@postgis:5432/geoapi_db

    depends_on:
      - postgis
  postgis:
    image: postgis/postgis:13-3.1
    container_name: postgis_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geoapi_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  #opensensemap_toolbox:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  volumes:
  #    - ./data:/osm_toolbox/OpenSenseMapToolbox
  #    - ./osm_toolbox/OpenSenseMapToolbox:/osm_toolbox/OpenSenseMapToolbox
  #  environment:
  #    - DATABASE_URL=postgresql://postgres:postgres@postgis:5432/geoapi_db
  #  depends_on:
  #    - postgis


volumes:
  db_data: 